---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  tasks:
  - name: Source neurodebian
    get_url:
      url: http://neuro.debian.net/lists/xenial.au.full
      dest: /etc/apt/sources.list.d/neurodebian.sources.list
  - name: apt keys
    apt_key:
      url: http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xA5D32F012649A5A9
      state: present
  - name: kill automatic updating script, if any
    command: pkill --full /usr/bin/unattended-upgrade
    register: kill_result
    failed_when: kill_result.rc > 1 # rc == 1 if the script is inactive
    changed_when: kill_result.rc == 0
  - name: Install ubuntu-desktop
    apt:
      name: ubuntu-desktop
      state: present
      update_cache: yes
  - name: Install FSL
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - fsl-complete
  - name: Download latest stable version of freesurfer
    get_url:
      url: 'ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz'
      dest: '/home/ubuntu/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz'
      validate_certs: no
  - name: Install freesurfer
    command: "tar -C /usr/local -xzvf /home/ubuntu/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz"
  - name: Download mricron
    get_url:
      url: 'https://www.nitrc.org/frs/download.php/9322/lx.zip//?i_agree=1&download_now=1'
      dest: '/home/ubuntu/lx.zip'
  - name: Install mricron
    command: "unzip /home/ubuntu/lx.zip -d /home/ubuntu"
  - name: Download ITK-SNAP
    get_url:
      url: 'https://downloads.sourceforge.net/project/itk-snap/itk-snap/3.6.0/itksnap-3.6.0-20170401-Linux-x86_64.tar.gz?r=http%3A%2F%2Fwww.itksnap.org%2Fdownload%2Fsnap%2Fprocess.php%3Flink%3D9997%26root%3Dnitrc&ts=1508129189&use_mirror=phoenixnap'
      dest: '/home/ubuntu/itksnap-3.6.0-20170401-Linux-x86_64.tar.gz'
  - name: Install ITK snap
    command: "tar -C /usr/local -zxvf /home/ubuntu/itksnap-3.6.0-20170401-Linux-x86_64.tar.gz"
...
