#Ansible playbook for setting up ubuntu-desktop, freesurfer 6.0, and FSL & ITK Snap
---
- hosts: all
  become: yes
  tasks:
  - name: Source neurodebian
    get_url:
      url: http://neuro.debian.net/lists/xenial.au.full
      dest: /etc/apt/sources.list.d/neurodebian.sources.list
  - name: apt keys
    apt_key:
      url: http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xA5D32F012649A5A9
      state: present
  - name: kill automatic updating script, if any
    command: pkill --full /usr/bin/unattended-upgrade
    register: kill_result
    failed_when: kill_result.rc > 1 # rc == 1 if the script is inactive
    changed_when: kill_result.rc == 0
  - name: update apt
    command: "apt-get update"
  - name: Install ubuntu-desktop and FSL
    apt:
      name: '{{ item }}'
      state: present
      update_cache: yes
    with_items:
      - ubuntu-desktop
      - fsl-complete
  - name: Install ITK snap
    command: "tar -C /usr/local -zxvf /home/vagrant/itksnap-3.6.0-20170401-Linux-x86_64.tar.gz"
  - name: Install freesurfer
    command: "tar -C /usr/local -xzvf /home/vagrant/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz"
...
