---
- hosts: all
  become: yes
  tasks:
  - name: Source neurodebian
    get_url:
      url: http://neuro.debian.net/lists/xenial.au.full
      dest: /etc/apt/sources.list.d/neurodebian.sources.list
  - name: apt keys
    apt_key:
      url: http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xA5D32F012649A5A9
      state: present
  - name: kill automatic updating script, if any
    command: pkill --full /usr/bin/unattended-upgrade
    register: kill_result
    failed_when: kill_result.rc > 1 # rc == 1 if the script is inactive
    changed_when: kill_result.rc == 0
  - name: update apt
    command: "apt-get update"
  - name: Install ubuntu-desktop
    apt:
      name: ubuntu-desktop
      state: present
      update_cache: yes
  - name: Install FSL
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - fsl-complete
...
